Update postrm

diff --git a/mjpg-streamer-experimental/debian/postrm b/mjpg-streamer-experimental/debian/postrm
--- a/mjpg-streamer-experimental/debian/postrm
+++ b/mjpg-streamer-experimental/debian/postrm
@@ -1,2 +1,76 @@
 #!/bin/sh
-userdel -fr mjpg_streamer
+# postrm script for mjpgstreamer
+#
+# see: dh_installdeb(1)
+
+set -e
+
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+REMOVE_DIRS=false
+REMOVE_USER_AND_GROUP=false
+
+
+case "$1" in
+    remove)
+        REMOVE_DIRS=true
+    ;;
+
+    purge)
+        REMOVE_DIRS=true
+        REMOVE_USER_AND_GROUP=true
+    ;;
+
+    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    ;;
+
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+if [ "$REMOVE_DIRS" = "true" ]; then
+
+    if [ -d /var/log/mjpg-streamer ]; then
+        echo -n "Deleting log directory..."
+        rm -rf /var/log/mjpg-streamer
+        echo " OK"
+    fi
+
+    if [ -d /var/run/mjpg-streamer ]; then
+        echo -n "Deleting PID directory..."
+        rm -rf /var/run/mjpg-streamer
+        echo " OK"
+    fi
+
+fi
+
+if [ "$REMOVE_USER_AND_GROUP" = "true" ]; then
+    if id mjpg_streamer > /dev/null 2>&1 ; then
+        userdel mjpg_streamer
+    fi
+
+    if getent group mjpg_streamer > /dev/null 2>&1 ; then
+        groupdel mjpg_streamer
+    fi
+fi
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
+#userdel -fr mjpg_streamer
